name: Despliega a Azure

on: [push]

jobs:
  prueba:
    runs-on: ubuntu-latest
    steps:
      - run: echo "job de prueba para dar tiempo a que Azure se actualice"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        name: Copiar archivo mediante ssh password

      - uses: appleboy/scp-action@v0.1.4
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
        with:
          KEY: ${{ secrets.SSHKEY }}
          source: "index.html"
          target: "/var/www/html"
